# .air.toml

# The command to run when everything is ready
[build]
  cmd = "go build -o ./bin/main ./cmd/main.go"
  bin = "bin/main"
  log = "tmp/build-errors.log"

# Watch these directories for changes
[watch]
  # List of search paths
  includes = [
    "cmd/**/*",
    "app/**/*",
    "bin/**/*"
  ]
  delay = 1000 # in milliseconds

# Configurations for log output
[log]
  level = "info"
  color = true


# Send interrupt signal before killing process
kill_delay = 2000 # in milliseconds
